//COMMON
export const COMMON_LOADING_SHOW = 'COMMON_LOADING_SHOW'
export const COMMON_LOADING_HIDE = 'COMMON_LOADING_HIDE'
export const COMMON_CHANGECITYNAME = 'COMMON_CHANGECITYNAME'
export const IS_LOGIN = 'IS_LOGIN'
export const ISAPP = 'ISAPP'
export const HIDENAVIGATEBAR = 'HIDENAVIGATEBAR'
    // 招聘
export const APPLY_HEADER_SHOW = 'APPLY_HEADER_SHOW'
export const APPLY_FOOTER_SHOW = 'APPLY_FOOTER_SHOW'
export const APPLY_INFO_LIST = 'APPLY_INFO_LIST'
    // microsite
export const HOSPITALINFO_UNIT_ID = 'HOSPITALINFO_UNIT_ID'
export const HOSPITALINFO_FOCUS_STATE = 'HOSPITALINFO_FOCUS_STATE'
export const HOSPITALINFO_BANNER = 'HOSPITALINFO_BANNER'
    // 医生说分享
export const DOCTORSAID_WXSHARE = 'DOCTORSAID_WXSHARE'

//健康
export const HEALTH_GETPRODUCTINFO_SUCESS = 'HEALTH_GETPRODUCTINFO_SUCESS'
export const HEALTH_GETPRODUCTINFO_FAIL = 'HEALTH_GETPRODUCTINFO_FAIL'
export const HEALTH_GETDEFAULTCATE = 'HEALTH_GETDEFAULTCATE'
export const HEALTH_GETCOUNT = 'HEALTH_GETCOUNT'
export const HEALTH_GETPAYMETHOD = 'HEALTH_GETPAYMETHOD'

// IM
export const IM = Object.freeze({
  nameSpace: 'IM',
  GETTOKEN:'GETTOKEN',
  GET_VISITINFO:'GET_VISITINFO',
  GET_LEFTNUM:'GET_LEFTNUM',
  MASKBOX_SHOW:'MASKBOX_SHOW',
  FUNCBOX_SHOW:'FUNCBOX_SHOW',
  FUNCBOX_HIDE:'FUNCBOX_HIDE',
  SETREPLYCOUNT:'SETREPLYCOUNT',
  CHANGEREPLYCOUNT:'CHANGEREPLYCOUNT',
  LEFTHOUR:'LEFTHOUR',
  HIDEINPUTBOX:'HIDEINPUTBOX',
  SHOWINPUTBOX:'SHOWINPUTBOX'
})

export const customize = Object.freeze({
	GETDATA:'GETDATA',
	GETCOMMENTLIST:'GETCOMMENTLIST',
	GETGHDEP:'GETGHDEP',
	GETHPBRANCH:'GETHPBRANCH',
	CHANGEACTIVEDEPID:'CHANGEACTIVEDEPID',
	SHOWVIDEOICON:'SHOWVIDEOICON'
})

// healthindex
export const healthindex = Object.freeze({
  INITCATEGORYINFO:'INITCATEGORYINFO',
  GETCATEGORYGOODS:'GETCATEGORYGOODS',
  CHANGECITYNAME:'CHANGECITYNAME',
  INITARTICLECATEGORY:'INITARTICLECATEGORY',
  CHANGEBEAUTYTAB:'CHANGEBEAUTYTAB',
  GETDIARYLIST:'GETDIARYLIST',
  GETBAIKELIST:'GETBAIKELIST',
  GETQUESTIONLIST:'GETQUESTIONLIST',
  CHANGECATEGORYID:'CHANGECATEGORYID',
  INITSHOWTYPE:'INITSHOWTYPE',
  INIYDAIRYANDADD:'INIYDAIRYANDADD',
  INITINDEXADD:'INITINDEXADD',
  INITUNITINFO:'INITUNITINFO',
  INITBEAUTYADD:'INITBEAUTYADD',
})
